# Generated by Django 5.2.4 on 2025-07-16 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_transactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviatorbet',
            name='cashed_out_at',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviatorbet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 16, 11, 25, 13, 960835, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aviatorbet',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
