# Generated by Django 5.2.1 on 2025-07-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_aviatorbet_cashed_out_at_aviatorbet_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviatorbet',
            old_name='cashed_out_at',
            new_name='final_multiplier',
        ),
    ]
