# Generated by Django 5.2.4 on 2025-07-19 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_cashed_out_at_aviatorbet_final_multiplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviatorbet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aviator_bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sureodd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sure_odds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
