# Generated by Django 5.2.4 on 2025-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_aviatorbet_user_alter_sureodd_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviatorround',
            name='crash_multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
