# Generated by Django 5.2.4 on 2025-07-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_aviatorround_delay_before_next_aviatorround_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviatorbet',
            name='auto_cashout',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
