# Generated by Django 5.2.4 on 2025-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_aviatorbet_auto_cashout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashMultiplierSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('weight', models.PositiveIntegerField(help_text='Relative weight for this range (e.g. 80 = 80%)')),
            ],
            options={
                'verbose_name': 'Crash Multiplier Setting',
                'verbose_name_plural': 'Crash Multiplier Settings',
            },
        ),
    ]
