services:
  # Django Web Service
  - type: web
    name: gamblegalaxy-backend
    runtime: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      daphne -b 0.0.0.0 -p $PORT gamblegalaxy.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gamblegalaxy-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: gamblegalaxy.onrender.com,localhost,127.0.0.1,[::1],192.168.100.12,gamble-galaxy.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://gamble-galaxy.vercel.app,http://localhost:3000,http://192.168.100.12,https://gamblegalaxy.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://gamblegalaxy.onrender.com,https://gamble-galaxy.vercel.app
      - key: FOOTBALL_API_KEY
        value: 433af63d5d2af7799890c753a53fe758
      - key: REDIS_URL
        fromService:
          type: redis
          name: gamblegalaxy-redis
          property: connectionString
    healthCheckPath: /api/health/
    autoDeploy: true

  # Redis Service for WebSocket Channel Layer
  - type: redis
    name: gamblegalaxy-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

databases:
  # PostgreSQL Database
  - name: gamblegalaxy-db
    plan: starter
    databaseName: gamblegalaxy
    user: gamblegalaxy_user