# Generated by Django 5.2.4 on 2025-07-15 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_time', models.DateTimeField()),
                ('odds_home_win', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_draw', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_away_win', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_option', models.CharField(choices=[('home_win', 'Home Win'), ('draw', 'Draw'), ('away_win', 'Away Win')], max_length=10)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.match')),
            ],
        ),
    ]
