# Generated by Django 5.2.4 on 2025-08-16 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_match_id', models.CharField(max_length=20, unique=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_time', models.DateTimeField()),
                ('status', models.CharField(default='upcoming', max_length=20)),
                ('score_home', models.IntegerField(default=0)),
                ('score_away', models.IntegerField(default=0)),
                ('halftime_score_home', models.IntegerField(blank=True, null=True)),
                ('halftime_score_away', models.IntegerField(blank=True, null=True)),
                ('elapsed_time', models.IntegerField(blank=True, null=True)),
                ('odds_home_win', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_away_win', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_over_2_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_under_2_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_btts_yes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_btts_no', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_home_or_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_draw_or_away', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_home_or_away', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_ht_ft_home_home', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_ht_ft_draw_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_ht_ft_away_away', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_score_1_0', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_score_2_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_score_0_0', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odds_score_1_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=50)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.bet')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.match')),
            ],
        ),
        migrations.CreateModel(
            name='SureOddSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_used', models.BooleanField(default=False)),
                ('shown_to_user_at', models.DateTimeField(auto_now_add=True)),
                ('revealed_predictions', models.BooleanField(default=False)),
                ('matches', models.ManyToManyField(to='betting.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SureOddPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_option', models.CharField(max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.match')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='betting.sureoddslip')),
            ],
        ),
    ]
