# Generated by Django 5.2.4 on 2025-08-05 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_time', models.DateTimeField()),
                ('odds_home_win', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_draw', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_away_win', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_over_2_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_under_2_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_btts_yes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_btts_no', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_home_or_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_draw_or_away', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_home_or_away', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_ht_ft_home_home', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_ht_ft_draw_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_ht_ft_away_away', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_score_1_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_score_2_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_score_0_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_score_1_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('first_half', 'First Half'), ('halftime', 'Half Time'), ('second_half', 'Second Half'), ('fulltime', 'Full Time')], default='upcoming', max_length=20)),
                ('score_home', models.IntegerField(default=0)),
                ('score_away', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_odds', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('expected_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betting.match')),
            ],
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('home_win', 'Home Win'), ('draw', 'Draw'), ('away_win', 'Away Win'), ('over_2.5', 'Over 2.5 Goals'), ('under_2.5', 'Under 2.5 Goals'), ('btts_yes', 'Both Teams to Score - Yes'), ('btts_no', 'Both Teams to Score - No'), ('home_or_draw', 'Home or Draw'), ('draw_or_away', 'Draw or Away'), ('home_or_away', 'Home or Away'), ('ht_ft_home_home', 'HT/FT Home/Home'), ('ht_ft_draw_draw', 'HT/FT Draw/Draw'), ('ht_ft_away_away', 'HT/FT Away/Away'), ('score_1_0', 'Correct Score 1-0'), ('score_2_1', 'Correct Score 2-1'), ('score_0_0', 'Correct Score 0-0'), ('score_1_1', 'Correct Score 1-1')], max_length=30)),
                ('odds', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.bet')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.match')),
            ],
        ),
        migrations.CreateModel(
            name='SureOddSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('has_paid', models.BooleanField(default=False)),
                ('shown_to_user_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('revealed_predictions', models.BooleanField(default=False)),
                ('matches', models.ManyToManyField(to='betting.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SureOddPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_option', models.CharField(choices=[('home_win', 'Home Win'), ('draw', 'Draw'), ('away_win', 'Away Win'), ('over_2.5', 'Over 2.5 Goals'), ('under_2.5', 'Under 2.5 Goals'), ('btts_yes', 'Both Teams to Score - Yes'), ('btts_no', 'Both Teams to Score - No'), ('home_or_draw', 'Home or Draw'), ('draw_or_away', 'Draw or Away'), ('home_or_away', 'Home or Away'), ('ht_ft_home_home', 'HT/FT Home/Home'), ('ht_ft_draw_draw', 'HT/FT Draw/Draw'), ('ht_ft_away_away', 'HT/FT Away/Away'), ('score_1_0', 'Correct Score 1-0'), ('score_2_1', 'Correct Score 2-1'), ('score_0_0', 'Correct Score 0-0'), ('score_1_1', 'Correct Score 1-1')], max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.match')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='betting.sureoddslip')),
            ],
        ),
    ]
