# Generated by Django 5.2.4 on 2025-07-15 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='match',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='odds',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='bet',
            name='total_odds',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='match',
            name='score_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('first_half', 'First Half'), ('halftime', 'Half Time'), ('second_half', 'Second Half'), ('fulltime', 'Full Time')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('home_win', 'Home Win'), ('draw', 'Draw'), ('away_win', 'Away Win')], max_length=10)),
                ('is_correct', models.BooleanField(blank=True, help_text='Set to True if the prediction was correct, False if not, None if pending.', null=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.bet')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.match')),
            ],
        ),
    ]
