# Generated by Django 5.2.4 on 2025-07-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_sureoddslip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sureoddslip',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sureoddslip',
            name='revealed_predictions',
            field=models.BooleanField(default=False),
        ),
    ]
