# Generated by Django 5.2.1 on 2025-07-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_remove_sureoddslip_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='expected_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
