# Generated by Django 5.2.1 on 2025-07-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_bet_expected_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betting.match'),
        ),
    ]
