# Generated by Django 5.2.1 on 2025-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_bet_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='betselection',
            name='odds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
